/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Select, Selection } from "@react-three/postprocessing";

export function Chair1({ hovered, setHovered, debouncedHover, over }) {
  //console.log(hovered, setHovered, debouncedHover, over);
  const { nodes, materials } = useGLTF("/HCH290S-451A/HCH290S-451A-opt.glb");
  return (
    <Select
      enabled={hovered === "Chair1"}
      onPointerOver={over("Chair1")}
      onPointerOut={() => debouncedHover(null)}
    >
      <group dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#0"].geometry}
          material={materials.material_08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#2"].geometry}
          material={materials.material_04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#5"].geometry}
          material={materials.material_05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#8"].geometry}
          material={materials.material_07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#9"].geometry}
          material={materials.material_09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#15"].geometry}
          material={materials.material_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#17"].geometry}
          material={materials.material_10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["meshobj#20"].geometry}
          material={materials.material_01}
        />
      </group>
    </Select>
  );
}

useGLTF.preload("/HCH290S-451A/HCH290S-451A-opt.glb");
